name: frontend
on:
  pull_request:
    type: 
      - opened
    branches:
      - master
      - develop
      - release-*
      - pre-release-*
      - zta-qa
    paths:
      - 'frontend/**'
  push:
    branches:
      - develop     # Development Environment
      - feature-*
      - craas-feature
      - zta-qa
    paths:
      - 'frontend/**'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  docker:
    name: Docker
    uses: ./.github/workflows/reusable-horusec-build-deploy-workflow.yml
    with:
      service_name: frontend
      service_path: frontend
      docker_registry: ghcr.io/extremenetworks/web-controller
    secrets:
      aws_access_key_ztna: ${{ secrets.AWS_ACCESS_KEY_ZTNA }}
      aws_secret_key_ztna: ${{ secrets.AWS_SECRET_KEY_ZTNA }}
      horusec_s3_bucket: ${{ secrets.HORUSEC_S3_BUCKET }}
      horusec_s3_key: ${{ secrets.HORUSEC_S3_KEY }}
      slack_channel_webhook: ${{ secrets.SLACK_CHANNEL_WEBHOOK }}
      slack_horusec_channel_webhook: ${{ secrets.SLACK_HORUSEC_CHANNEL_WEBHOOK }}
      jira_base_url: ${{ secrets.JIRA_BASE_URL }}
      jira_user_email: ${{ secrets.JIRA_USER_EMAIL }}
      jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
      gcr_token_ztna: ${{ secrets.GCR_TOKEN_ZTNA }}
      repo_owner_ztna: ${{ secrets.REPO_OWNER_ZTNA }}
      gcr_token: ${{ secrets.GCR_TOKEN }}
      aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
      send_grid_token: ${{ secrets.SEND_GRID_TOKEN }}
      google_sa_secret: ${{secrets.GOOGLE_SA_SECRET}}
      gsheet_id: ${{secrets.GSHEET_ID}}
      react_app_location_api_key: ${{ secrets.REACT_APP_LOCATION_API_KEY }}
      react_app_pendo_api_key_dev: ${{ secrets.REACT_APP_PENDO_API_KEY_DEV }}
      react_app_pendo_api_key_qa: ${{ secrets.REACT_APP_PENDO_API_KEY_QA }}
      react_app_pendo_api_key_demo: ${{ secrets.REACT_APP_PENDO_API_KEY_DEMO }}
