name: Run Trivy Security Scan
on:
    workflow_call:
jobs:
  run-trivy-security-scan:
    name: Run Trivy Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Trivy
        run: 'echo "No Trivy Scan Required. Test passed!"'